### ISSUE TITLE
Crash in xi_edit_view_real_key_press_event

### ISSUE THREAD

**Issue by raphlinus** [eyelash/xi-gtk#42]
Any time I press a key I get a crash. Here's the full backtrace:

```
starting plugins for view-id-1
[New Thread 0x7fffe79b0700 (LWP 238554)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7218472 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
(gdb) bt
#0  0x00007ffff7218472 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#1  0x00007ffff724eeae in gdk_x11_window_get_xid ()
   from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#2  0x00007fffe6fac0ca in ?? ()
   from /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-xim.so
#3  0x00007ffff76da013 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x0000555555563cc6 in xi_edit_view_real_key_press_event (
    base=0x555555a8f890, event=0x555555aef210)
    at /usr/local/google/home/raph/github/xi-gtk/src/EditView.vala:154
#5  0x00007ffff76fa31a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff648b0f2 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff64a53a1 in g_signal_emit_valist ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff64a5fbf in g_signal_emit ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff78469bc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff786750b in gtk_window_propagate_key_event ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff786b03b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff76fa31a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff648b1a4 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff64a53a1 in g_signal_emit_valist ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff64a5fbf in g_signal_emit ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff78469bc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff76f7339 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff76f935e in gtk_main_do_event ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff7208405 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#20 0x00007ffff72397d2 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#21 0x00007ffff61b17f7 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007ffff61b1a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff61b1b0c in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff676d72d in g_application_run ()
   from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#25 0x000055555555c0c6 in xi_application_main (args=0x7fffffffded8, 
    args_length1=1)
    at /usr/local/google/home/raph/github/xi-gtk/src/Application.vala:87
#26 0x000055555555c10f in main (argc=1, argv=0x7fffffffded8)
    at /usr/local/google/home/raph/github/xi-gtk/src/Application.vala:85
```

This is a Debian Testing based machine, running Cinnamon desktop. 
The version of libgtk-3-0 is 3.22.24-3

I'll see if I can grab any more debug info.

**Comment by raphlinus** [comment]
Here's a backtrace from a debug build:

```
#0  0x00007ffff7237a02 in gdk_window_has_impl (window=<optimized out>)
    at gdkwindow.c:677
#1  _gdk_window_has_impl (window=window@entry=0x0) at gdkwindow.c:678
#2  0x00007ffff726c8be in gdk_x11_window_get_xid (window=0x0)
    at gdkwindow-x11.c:5560
#3  0x00007fffec005fd7 in gtk_im_context_xim_filter_keypress (
    context=0x5555557de3e0, event=0x7fffe0006e80) at gtkimcontextxim.c:673
#4  0x00007ffff76e2783 in gtk_im_multicontext_filter_keypress (
    context=0x555555b11c70, event=0x7fffe0006e80) at gtkimmulticontext.c:359
#5  0x0000555555563cc6 in xi_edit_view_real_key_press_event (
    base=0x555555aa8890, event=0x7fffe0006e80)
    at /usr/local/google/home/raph/github/xi-gtk/src/EditView.vala:154
```
